version: '3'
volumes:
  pgdata:
services:
  python:
    # image: python:3.6
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./first_app:/first_app
    ports:
      - 8000:8000
  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ecomuser
      POSTGRES_DB: ecom
      POSTGRES_PASS: testuser123
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5432:5432
